# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Sms

# Model Form Field configuration
form: $/joaquinb/smssender/models/sms/fields.yaml

# Model Class name
modelClass: Joaquinb\Smssender\Models\Sms

# Default redirect location
defaultRedirect: joaquinb/smssender/sms

# Create page
create:
    title: Create Sms
    redirect: joaquinb/smssender/sms/
    redirectClose: joaquinb/smssender/sms